from tests import Base
from chinese.config import ConfigManager


class Config(Base):
    def test_get_fields(self):
        config = ConfigManager()
        expected = ['English', '英文', '英語', '英语']
        self.assertEqual(config.get_fields(['english']), expected)

    def test_get_fields_no_arg(self):
        config = ConfigManager()
        expected = [
            'Also Written',
            'Alternative',
            'Audio',
            'Bopomofo',
            'Cantonese',
            'Chinese',
            'Classifier',
            'Color Hanzi',
            'Color',
            'Deutsch',
            'English',
            'Expression',
            'French',
            'Frequency',
            'German',
            'Hanzi (Color)',
            'Hanzi',
            'Measure Word',
            'Pinyin (Taiwan)',
            'Pinyin',
            'Reading',
            'Ruby (Bopomofo)',
            'Ruby (Cantonese)',
            'Ruby (Pinyin)',
            'Ruby (Taiwan Pinyin)',
            'Ruby (Zhuyin)',
            'Ruby',
            'Silhouette',
            'Simp',
            'Simp.',
            'Simplified',
            'Sound (Cantonese)',
            'Sound (Mandarin)',
            'Sound',
            'Spoken',
            'Trad',
            'Trad.',
            'Traditional',
            'Zhuyin',
            'le français',
            'ㄅㄆㄇㄈ',
            '中文',
            '台湾拼音',
            '台灣拼音',
            '声音',
            '大陆拼音',
            '大陸拼音',
            '广东话',
            '广州话',
            '廣州話',
            '廣東話',
            '彩色',
            '德文',
            '德語',
            '德语',
            '拼音',
            '汉字',
            '法文',
            '法語',
            '法语',
            '注音符号',
            '注音符號',
            '漢字',
            '简体',
            '简体字',
            '简化',
            '简化字',
            '簡化',
            '簡化字',
            '簡體',
            '簡體字',
            '粤',
            '粤拼',
            '粤语',
            '粵',
            '粵拼',
            '粵語',
            '繁体',
            '繁体字',
            '繁體',
            '繁體字',
            '聲音',
            '臺灣拼音',
            '英文',
            '英語',
            '英语',
            '註音符號',
            '量詞',
            '量词',
        ]
        self.assertCountEqual(config.get_fields(), expected)
